# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-system-monitor
    - gcc
    - git
    - gtkmm3
    - intltool
    - libgtop
    - libwnck3
    - make
    - mate-common
    - mate-desktop
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-system-monitor
    - g++
    - git
    - intltool
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - quilt
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-system-monitor.git
    - gcc
    - gcc-c++
    - dbus-glib-devel
    - desktop-file-utils
    - git
    - gtk3-devel
    - gtkmm30-devel
    - libgtop2-devel
    - librsvg2-devel
    - libwnck3-devel
    - libxml2-devel
    - make
    - mate-common
    - redhat-rpm-config
    - systemd-devel

  ubuntu:
    - g++
    - git
    - intltool
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - quilt
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-system-monitor-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
